// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecrecyHeaders.proto

package com.doplgangr.secrecy.filesystem.files;

public final class SecrecyHeaders {
  private SecrecyHeaders() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VaultHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1;
    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    // required bytes vaultIV = 2;
    /**
     * <code>required bytes vaultIV = 2;</code>
     */
    boolean hasVaultIV();
    /**
     * <code>required bytes vaultIV = 2;</code>
     */
    com.google.protobuf.ByteString getVaultIV();

    // required bytes salt = 3;
    /**
     * <code>required bytes salt = 3;</code>
     */
    boolean hasSalt();
    /**
     * <code>required bytes salt = 3;</code>
     */
    com.google.protobuf.ByteString getSalt();

    // required int32 pbkdf2Iterations = 4;
    /**
     * <code>required int32 pbkdf2Iterations = 4;</code>
     */
    boolean hasPbkdf2Iterations();
    /**
     * <code>required int32 pbkdf2Iterations = 4;</code>
     */
    int getPbkdf2Iterations();

    // required bytes encryptedAesKey = 5;
    /**
     * <code>required bytes encryptedAesKey = 5;</code>
     */
    boolean hasEncryptedAesKey();
    /**
     * <code>required bytes encryptedAesKey = 5;</code>
     */
    com.google.protobuf.ByteString getEncryptedAesKey();
  }
  /**
   * Protobuf type {@code com.doplgangr.secrecy.FileSystem.Files.VaultHeader}
   */
  public static final class VaultHeader extends
      com.google.protobuf.GeneratedMessage
      implements VaultHeaderOrBuilder {
    // Use VaultHeader.newBuilder() to construct.
    private VaultHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VaultHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VaultHeader defaultInstance;
    public static VaultHeader getDefaultInstance() {
      return defaultInstance;
    }

    public VaultHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VaultHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              vaultIV_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              salt_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pbkdf2Iterations_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              encryptedAesKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader.class, com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<VaultHeader> PARSER =
        new com.google.protobuf.AbstractParser<VaultHeader>() {
      public VaultHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VaultHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VaultHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    // required bytes vaultIV = 2;
    public static final int VAULTIV_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString vaultIV_;
    /**
     * <code>required bytes vaultIV = 2;</code>
     */
    public boolean hasVaultIV() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes vaultIV = 2;</code>
     */
    public com.google.protobuf.ByteString getVaultIV() {
      return vaultIV_;
    }

    // required bytes salt = 3;
    public static final int SALT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString salt_;
    /**
     * <code>required bytes salt = 3;</code>
     */
    public boolean hasSalt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes salt = 3;</code>
     */
    public com.google.protobuf.ByteString getSalt() {
      return salt_;
    }

    // required int32 pbkdf2Iterations = 4;
    public static final int PBKDF2ITERATIONS_FIELD_NUMBER = 4;
    private int pbkdf2Iterations_;
    /**
     * <code>required int32 pbkdf2Iterations = 4;</code>
     */
    public boolean hasPbkdf2Iterations() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 pbkdf2Iterations = 4;</code>
     */
    public int getPbkdf2Iterations() {
      return pbkdf2Iterations_;
    }

    // required bytes encryptedAesKey = 5;
    public static final int ENCRYPTEDAESKEY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString encryptedAesKey_;
    /**
     * <code>required bytes encryptedAesKey = 5;</code>
     */
    public boolean hasEncryptedAesKey() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes encryptedAesKey = 5;</code>
     */
    public com.google.protobuf.ByteString getEncryptedAesKey() {
      return encryptedAesKey_;
    }

    private void initFields() {
      version_ = 0;
      vaultIV_ = com.google.protobuf.ByteString.EMPTY;
      salt_ = com.google.protobuf.ByteString.EMPTY;
      pbkdf2Iterations_ = 0;
      encryptedAesKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVaultIV()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSalt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPbkdf2Iterations()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedAesKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, vaultIV_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, salt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pbkdf2Iterations_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, encryptedAesKey_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, vaultIV_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, salt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pbkdf2Iterations_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, encryptedAesKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.doplgangr.secrecy.FileSystem.Files.VaultHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader.class, com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader.Builder.class);
      }

      // Construct using com.doplgangr.secrecy.FileSystem.Files.SecrecyHeaders.VaultHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        vaultIV_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        salt_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        pbkdf2Iterations_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        encryptedAesKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_descriptor;
      }

      public com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader getDefaultInstanceForType() {
        return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader.getDefaultInstance();
      }

      public com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader build() {
        com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader buildPartial() {
        com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader result = new com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vaultIV_ = vaultIV_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.salt_ = salt_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pbkdf2Iterations_ = pbkdf2Iterations_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.encryptedAesKey_ = encryptedAesKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader) {
          return mergeFrom((com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader other) {
        if (other == com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasVaultIV()) {
          setVaultIV(other.getVaultIV());
        }
        if (other.hasSalt()) {
          setSalt(other.getSalt());
        }
        if (other.hasPbkdf2Iterations()) {
          setPbkdf2Iterations(other.getPbkdf2Iterations());
        }
        if (other.hasEncryptedAesKey()) {
          setEncryptedAesKey(other.getEncryptedAesKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasVaultIV()) {
          
          return false;
        }
        if (!hasSalt()) {
          
          return false;
        }
        if (!hasPbkdf2Iterations()) {
          
          return false;
        }
        if (!hasEncryptedAesKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.VaultHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1;
      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required bytes vaultIV = 2;
      private com.google.protobuf.ByteString vaultIV_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes vaultIV = 2;</code>
       */
      public boolean hasVaultIV() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes vaultIV = 2;</code>
       */
      public com.google.protobuf.ByteString getVaultIV() {
        return vaultIV_;
      }
      /**
       * <code>required bytes vaultIV = 2;</code>
       */
      public Builder setVaultIV(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        vaultIV_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes vaultIV = 2;</code>
       */
      public Builder clearVaultIV() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vaultIV_ = getDefaultInstance().getVaultIV();
        onChanged();
        return this;
      }

      // required bytes salt = 3;
      private com.google.protobuf.ByteString salt_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes salt = 3;</code>
       */
      public boolean hasSalt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes salt = 3;</code>
       */
      public com.google.protobuf.ByteString getSalt() {
        return salt_;
      }
      /**
       * <code>required bytes salt = 3;</code>
       */
      public Builder setSalt(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        salt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes salt = 3;</code>
       */
      public Builder clearSalt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        salt_ = getDefaultInstance().getSalt();
        onChanged();
        return this;
      }

      // required int32 pbkdf2Iterations = 4;
      private int pbkdf2Iterations_ ;
      /**
       * <code>required int32 pbkdf2Iterations = 4;</code>
       */
      public boolean hasPbkdf2Iterations() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 pbkdf2Iterations = 4;</code>
       */
      public int getPbkdf2Iterations() {
        return pbkdf2Iterations_;
      }
      /**
       * <code>required int32 pbkdf2Iterations = 4;</code>
       */
      public Builder setPbkdf2Iterations(int value) {
        bitField0_ |= 0x00000008;
        pbkdf2Iterations_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pbkdf2Iterations = 4;</code>
       */
      public Builder clearPbkdf2Iterations() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pbkdf2Iterations_ = 0;
        onChanged();
        return this;
      }

      // required bytes encryptedAesKey = 5;
      private com.google.protobuf.ByteString encryptedAesKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes encryptedAesKey = 5;</code>
       */
      public boolean hasEncryptedAesKey() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes encryptedAesKey = 5;</code>
       */
      public com.google.protobuf.ByteString getEncryptedAesKey() {
        return encryptedAesKey_;
      }
      /**
       * <code>required bytes encryptedAesKey = 5;</code>
       */
      public Builder setEncryptedAesKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        encryptedAesKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes encryptedAesKey = 5;</code>
       */
      public Builder clearEncryptedAesKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        encryptedAesKey_ = getDefaultInstance().getEncryptedAesKey();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.doplgangr.secrecy.FileSystem.Files.VaultHeader)
    }

    static {
      defaultInstance = new VaultHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.doplgangr.secrecy.FileSystem.Files.VaultHeader)
  }

  public interface FileHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1;
    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    // required bytes fileIV = 2;
    /**
     * <code>required bytes fileIV = 2;</code>
     */
    boolean hasFileIV();
    /**
     * <code>required bytes fileIV = 2;</code>
     */
    com.google.protobuf.ByteString getFileIV();

    // required bytes fileNameIV = 3;
    /**
     * <code>required bytes fileNameIV = 3;</code>
     */
    boolean hasFileNameIV();
    /**
     * <code>required bytes fileNameIV = 3;</code>
     */
    com.google.protobuf.ByteString getFileNameIV();

    // required bytes encryptedFileName = 6;
    /**
     * <code>required bytes encryptedFileName = 6;</code>
     */
    boolean hasEncryptedFileName();
    /**
     * <code>required bytes encryptedFileName = 6;</code>
     */
    com.google.protobuf.ByteString getEncryptedFileName();
  }
  /**
   * Protobuf type {@code com.doplgangr.secrecy.FileSystem.Files.FileHeader}
   */
  public static final class FileHeader extends
      com.google.protobuf.GeneratedMessage
      implements FileHeaderOrBuilder {
    // Use FileHeader.newBuilder() to construct.
    private FileHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileHeader defaultInstance;
    public static FileHeader getDefaultInstance() {
      return defaultInstance;
    }

    public FileHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fileIV_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fileNameIV_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000008;
              encryptedFileName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader.class, com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<FileHeader> PARSER =
        new com.google.protobuf.AbstractParser<FileHeader>() {
      public FileHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    // required bytes fileIV = 2;
    public static final int FILEIV_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString fileIV_;
    /**
     * <code>required bytes fileIV = 2;</code>
     */
    public boolean hasFileIV() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes fileIV = 2;</code>
     */
    public com.google.protobuf.ByteString getFileIV() {
      return fileIV_;
    }

    // required bytes fileNameIV = 3;
    public static final int FILENAMEIV_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString fileNameIV_;
    /**
     * <code>required bytes fileNameIV = 3;</code>
     */
    public boolean hasFileNameIV() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes fileNameIV = 3;</code>
     */
    public com.google.protobuf.ByteString getFileNameIV() {
      return fileNameIV_;
    }

    // required bytes encryptedFileName = 6;
    public static final int ENCRYPTEDFILENAME_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString encryptedFileName_;
    /**
     * <code>required bytes encryptedFileName = 6;</code>
     */
    public boolean hasEncryptedFileName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes encryptedFileName = 6;</code>
     */
    public com.google.protobuf.ByteString getEncryptedFileName() {
      return encryptedFileName_;
    }

    private void initFields() {
      version_ = 0;
      fileIV_ = com.google.protobuf.ByteString.EMPTY;
      fileNameIV_ = com.google.protobuf.ByteString.EMPTY;
      encryptedFileName_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileIV()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileNameIV()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptedFileName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, fileIV_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, fileNameIV_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(6, encryptedFileName_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, fileIV_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, fileNameIV_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, encryptedFileName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.doplgangr.secrecy.FileSystem.Files.FileHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader.class, com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader.Builder.class);
      }

      // Construct using com.doplgangr.secrecy.FileSystem.Files.SecrecyHeaders.FileHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fileIV_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        fileNameIV_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        encryptedFileName_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_descriptor;
      }

      public com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader getDefaultInstanceForType() {
        return com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader.getDefaultInstance();
      }

      public com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader build() {
        com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader buildPartial() {
        com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader result = new com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileIV_ = fileIV_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fileNameIV_ = fileNameIV_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.encryptedFileName_ = encryptedFileName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader) {
          return mergeFrom((com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader other) {
        if (other == com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasFileIV()) {
          setFileIV(other.getFileIV());
        }
        if (other.hasFileNameIV()) {
          setFileNameIV(other.getFileNameIV());
        }
        if (other.hasEncryptedFileName()) {
          setEncryptedFileName(other.getEncryptedFileName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasFileIV()) {
          
          return false;
        }
        if (!hasFileNameIV()) {
          
          return false;
        }
        if (!hasEncryptedFileName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.doplgangr.secrecy.filesystem.files.SecrecyHeaders.FileHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1;
      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required bytes fileIV = 2;
      private com.google.protobuf.ByteString fileIV_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes fileIV = 2;</code>
       */
      public boolean hasFileIV() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes fileIV = 2;</code>
       */
      public com.google.protobuf.ByteString getFileIV() {
        return fileIV_;
      }
      /**
       * <code>required bytes fileIV = 2;</code>
       */
      public Builder setFileIV(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileIV_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes fileIV = 2;</code>
       */
      public Builder clearFileIV() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileIV_ = getDefaultInstance().getFileIV();
        onChanged();
        return this;
      }

      // required bytes fileNameIV = 3;
      private com.google.protobuf.ByteString fileNameIV_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes fileNameIV = 3;</code>
       */
      public boolean hasFileNameIV() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes fileNameIV = 3;</code>
       */
      public com.google.protobuf.ByteString getFileNameIV() {
        return fileNameIV_;
      }
      /**
       * <code>required bytes fileNameIV = 3;</code>
       */
      public Builder setFileNameIV(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fileNameIV_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes fileNameIV = 3;</code>
       */
      public Builder clearFileNameIV() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fileNameIV_ = getDefaultInstance().getFileNameIV();
        onChanged();
        return this;
      }

      // required bytes encryptedFileName = 6;
      private com.google.protobuf.ByteString encryptedFileName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes encryptedFileName = 6;</code>
       */
      public boolean hasEncryptedFileName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes encryptedFileName = 6;</code>
       */
      public com.google.protobuf.ByteString getEncryptedFileName() {
        return encryptedFileName_;
      }
      /**
       * <code>required bytes encryptedFileName = 6;</code>
       */
      public Builder setEncryptedFileName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        encryptedFileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes encryptedFileName = 6;</code>
       */
      public Builder clearEncryptedFileName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        encryptedFileName_ = getDefaultInstance().getEncryptedFileName();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.doplgangr.secrecy.FileSystem.Files.FileHeader)
    }

    static {
      defaultInstance = new FileHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.doplgangr.secrecy.FileSystem.Files.FileHeader)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SecrecyHeaders.proto\022&com.doplgangr.se" +
      "crecy.FileSystem.Files\"p\n\013VaultHeader\022\017\n" +
      "\007version\030\001 \002(\005\022\017\n\007vaultIV\030\002 \002(\014\022\014\n\004salt\030" +
      "\003 \002(\014\022\030\n\020pbkdf2Iterations\030\004 \002(\005\022\027\n\017encry" +
      "ptedAesKey\030\005 \002(\014\"\\\n\nFileHeader\022\017\n\007versio" +
      "n\030\001 \002(\005\022\016\n\006fileIV\030\002 \002(\014\022\022\n\nfileNameIV\030\003 " +
      "\002(\014\022\031\n\021encryptedFileName\030\006 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_doplgangr_secrecy_FileSystem_Files_VaultHeader_descriptor,
              new java.lang.String[] { "Version", "VaultIV", "Salt", "Pbkdf2Iterations", "EncryptedAesKey", });
          internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_doplgangr_secrecy_FileSystem_Files_FileHeader_descriptor,
              new java.lang.String[] { "Version", "FileIV", "FileNameIV", "EncryptedFileName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
